name: Build and Publish image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api/ -t mud2003/qr-api:latest
          docker build ./front-end-nextjs/ -t mud2003/qr-frontend:latest
      - name: push image to docker hub
        run: |
          docker login -u mud2003 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push mud2003/qr-api:latest
          docker push mud2003/qr-frontend:latest